### PR TITLE
🎉 Add CMake support and basic compiling with C++14

### PR DESCRIPTION
**Pull request by bruxisma**
Apologies for the last two misfire PRs. They were made with a work account and not my personal one 🤦

A brief summary of squash commits that are all within this one:

🔨 Fix linker warning regarding default libraries
🔨 Enable C compiler in CMake
🔨 Add CMakePresets.json
🔨 Add cmake/FindAudioMan.cmake
🔨 Add cmake/FindClangTidy.cmake
🔨 Add cmake/FindCCache.cmake
🔨 Add cmake/FindBRender.cmake
♻️ Remove DLL form of MSVC_RUNTIME_LIBRARY
🐛 Fix missing C files for BRender library
🐛 Fix typo in cmake/FindBRender.cmake
🩹 Add temporary stub files for audioman within kauai library
🚚 Move BREN/*.C files to be lowercase

Explanation
-----------

This is because CMake (and most C++ compilers on other platforms!) assume that .C is a C++ file (yeah I don't know why either)

This now compiles in a (mostly) clean manner while still letting a few MSVC extensions make its way through. A lot more work is needed to make it compile cleanly with clang-tidy or even just clang with no warnings enabled.

There are a few warnings that are legitimate bugs but these are not the focus of this change.

I've also adjusted the README to support the workflow I'm using for this regarding configure+build steps.

What's left to do (in other PRs!):

- [x] Add install() calls to put all binary files into their correct   location
- [x] Generate CPack information so that a binary zip can be dropped into place as a "portable" build
- [x] Generate optional installers via CPack
- [x] Get any TOOLS/ building as part of the process

However what's been provided here should work as a good starting base.

This change incorporates a few things from @clemenswasser and @frank-weindel, who deserve credit for figuring a few things out I had not run into yet, or who had solved a similar issue or two that I adopted to reduce conflicts or breakage.

Furthermore, a brief explanation of why I chose to use the `file(GLOB)` feature: speed. I doubt new files are going to be added anytime soon, the overhead (even on windows) of using the glob feature are 0.2s when building, and more time is spent linking and compiling than building the list of necessary files. If putting the files explicitly in every location is desired, I'll leave that up to someone else.

Additionally, I've written multiple versions in the past of cmake/ExtractVersion.cmake which contains a "magic regex" to find almost every version number in existence for executables. This should come in handy if needed to lock down external tooling to a minimum version range. This is just a copy paste from a personal project, and I'm giving it here under the MIT License instead of the Apache license so that additional copyright isn't needed.

The ClangTidy and CCache find packages were written from scratch using a [blog post I wrote](https://izzys.casa/2020/12/how-to-find-packages-with-cmake-the-basics/) at the very tail end of 2020. This can be used as a reference to understand why things are declared.

Lastly, the BRender and AudioMan `find_package` files are intended to act as a shim so that if the source for other BRender implementations are ever "massaged" to work with 3DMMForever, they can be dropped in place whether prebuilt or pulled in via CMake's `FetchContent` module. AudioMan is also given this treatment, to keep the CMakeLists.txt file more uniform

### CODE REVIEW

**Comment by BoofOof32** [comment]
perhaps this could be the first step for allowing compilation for Linux?

**Comment by bruxisma** [comment]
This does get us closer to that, yes.

**Comment by LowLevelMahn** [comment]
> Lastly, the BRender and AudioMan `find_package` files are intended to act as a shim so that if the source for other BRender implementations are ever "massaged" to work with 3DMMForever

i've read that NCommander(or Foone) already able (with small tweaks) to use the BRender source code from Foones repos?

**Comment by bruxisma** [comment]
> i've read that NCommander(or Foone) already able (with small tweaks) to use the BRender source code from Foones repos?

I haven't been able to keep track of everything happening, but if we can CMake-ify an external BRender implementation, then we can use the `FetchContent` module to just pull it down to configure + build on demand (and in a way where CMake knows what the targets are and can reason about them).

It's more important to get it building with "not NMake" and "not VC 2.1" IMHO 😅

**Comment by LowLevelMahn** [comment]
> I haven't been able to keep track of everything happening, but if we can CMake-ify an external BRender implementation

i wouldn't say "external" - more a option to a) use the original 3DMM/BRender libs (we got from microsoft) or b) compile with the patched (to work with 3DMM) BRender source based on one of the two BRender repos from Foone (the 1997 version seems to be more equal, same files-names etc.)

**Comment by bruxisma** [comment]
> i wouldn't say "external" - more a option to a) use the original 3DMM/BRender libs (we got from microsoft) or b) compile with the patched (to work with 3DMM) BRender source based on one of the two BRender repos from Foone (the 1997 version seems to be more equal, same files-names etc.)

External in this sense means "code that is potentially hosted outside of the repository", such that if I were to just clone 3DMMForever, additional network operations could potentially take place during the configure stage (this is no different than what languages like Python, OCaml, Rust, Haskell, Perl, JS, C#, etc. all do with their supply chains), use a prebuilt version stored elsewhere on disk, or use the libraries that currently exist within the repository. All three are valid, and only a little work is needed to support these different paths.

**Comment by nsapa** [comment]
>  b) compile with the patched (to work with 3DMM) BRender source based on one of the two BRender repos from Foone (the 1997 version seems to be more equal, same files-names etc.)

@NCommander was able to rebuild BRender 1.1.2' libs and link them into 3DMM.
The build system use [dmake](https://github.com/jimjag/dmake) and a perl script named mkdep that is missing (it had to be hacked from BRender 1.3.2).
It still use VC 2.1 as compiler.
The repository is available [here](https://github.com/NCommander/3DMM-BRender/)

**Comment by bruxisma** [comment]
> @NCommander was able to rebuild BRender 1.1.2' libs and link them into 3DMM.
The build system use [dmake](https://github.com/jimjag/dmake) and a perl script named mkdep that is missing (it had to be hacked from BRender 1.3.2).
It still use VC 2.1 as compiler.
The repository is available [here](https://github.com/NCommander/3DMM-BRender/)

Fantastic. Sounds like something that *could* be CMake-ified so we can pull it down as an option. This would definitely help when moving to clang/gcc because of ABI stuff (AudioMan is still an issue 😔)

**Comment by dhrdlicka** [comment]
> This is because CMake (and most C++ compilers on other platforms!) assume that .C is a C++ file (yeah I don't know why either)

It is one of the conventions used on case-sensitive platforms (i.e. not Windows) to differentiate between C and C++ source files.

IMHO it might be best to just normalize all filenames in the repo to lowercase.

**Comment by bruxisma** [comment]
> It is one of the conventions used on case-sensitive platforms (i.e. not Windows) to differentiate between C and C++ source files.

Yes, I know, I was simply commenting that I do not know *why* that was ever made as a decision.

Any conversion to lowercase everywhere is going to be needed to at least satisfy non-Windows building at some point. However, that can be a separate PR.

**Pull request merged**
