### PR TITLE
Lowercase most files / folders

### LINKED ISSUE #40: Lower-case all remaining files and folders
Code files and folders were lower cased in #34

Let's rename all of them to lower case, unless there's a good reason not to for some files/folders.

### PR DESCRIPTION
**Pull request by frank-weindel**
Resolves #40 

Pretty much all original files and folders have been lower-cased. The ones that were not touched are mostly in the root or CMake directories. I've tested and the project still builds and runs properly via CMake.

### CODE REVIEW

**Comment by mdtauk** [comment]
I am assuming moving them to lowercase does not affect code compile.  And I am guessing the files likely need to remain 8.3 for compatibility?

**Comment by frank-weindel** [comment]
@mdtauk It does not affect compile. I've tested that. I'm not sure about 8.3. I don't think so as we aren't striving to maintain compatibility with the original build tools.

**Comment by foone** [comment]
Merged. And yeah, maintaining compatibility with original build tools isn't a goal. Besides, it was only limited to 8.3 because files might be transported through pre-Win95 systems, which is very unlikely at this stage.

**Comment by mdtauk** [comment]
That's good to hear then, it means the code base can become more verbose in it's method/function names, and be a bit more descriptive with file names.

On a slight tangent, as the codebase changes, is there any merit in decompiling there binary asset files like the scenes, cameras, midis, sound files etc.

With a recompile process at build/make?

**Comment by frank-weindel** [comment]
@mdtauk In the short term, at least, I'd say not. Given the already available dynamic expandability offered by v3dmm and what I assume is our desire to maintain compatibility with it until we migrate its functionality into 3DMMForever itself, I don't think we'll need to touch the existing built-in movie asset files for some time. Not sure what we might regularly change there that would warrant all of that complexity.

**Comment by frank-weindel** [comment]
It's worth noting that the building asset chunky files are already in source form and are compiled. We'd more likely make occasional changes to them.

**Pull request merged**
